# Generated by Django 4.2.4 on 2024-01-24 17:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(default=1, help_text='Selecione o estado da cidade de origem', on_delete=django.db.models.deletion.PROTECT, to='cadastros.uf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cachaca',
            name='cidade',
            field=models.ForeignKey(help_text='Selecione a cidade de origem', on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade'),
        ),
        migrations.AlterField(
            model_name='cachaca',
            name='teor',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Teor Alcoólico'),
        ),
        migrations.AlterField(
            model_name='cachaca',
            name='tipo',
            field=models.ForeignKey(help_text='Selecione o tipo da bebida', on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipo'),
        ),
        migrations.AlterField(
            model_name='cachaca',
            name='uf',
            field=models.ForeignKey(help_text='Selecione o estado da cidade de origem', on_delete=django.db.models.deletion.PROTECT, to='cadastros.uf'),
        ),
    ]
