# Generated by Django 4.2.4 on 2024-01-24 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_cidade_uf_alter_cachaca_cidade_alter_cachaca_teor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachaca',
            name='uf',
        ),
    ]
